### ISSUE TITLE
any documentation for agent.py?

### ISSUE THREAD

**Issue by tristansokol** [openai/retro-baselines#1]
I'm seeing it referenced in https://github.com/openai/retro-baselines/blob/master/agents/jerk.docker but don't understand how it works. Any guidance would be great!

**Comment by praveen-palanisamy** [comment]
`jerk_agent.py` is renamed to `agent.py` and stored in the container's working directory as per the `jerk.docker` file.
So, you can have a look at [`jerk_agent.py`](https://github.com/openai/retro-baselines/blob/master/agents/jerk_agent.py) which is the same as`agent.py`.

**Comment by tristansokol** [comment]
ahh, thank you! 

do you happen to know about the `baselines.common` code mentioned in the rainbow baseline?
https://github.com/openai/retro-baselines/blob/master/agents/sonic_util.py#L8

**Comment by praveen-palanisamy** [comment]
You are welcome.
The code for `baselines.common` is here: [https://github.com/openai/baselines/tree/master/baselines/common](https://github.com/openai/baselines/tree/master/baselines/common)

**Comment by tristansokol** [comment]
Thank you again!
